---
on: push
name: Run aspell
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install aspell
        run: sudo apt-get install aspell aspell-en
      - name: Run aspell
        run: |
          for i in `find . -name '*.markdown' `; do
            echo "Checking file name: $i"
            echo "------------------------------------------------------"
            cat $i | aspell --lang en --personal ./.aspell.en.pws list | tee -a typos.txt
          done
          if [ -s typo.txt ] then;
            echo "possible spell error(s)"
            echo "------------------------------------------------------"
            cat typos.txt
            echo "------------------------------------------------------"
            exit 1
          fi
